using Microsoft.AspNetCore.Mvc;

using api.Features.Account;
using api.Features.Auth.Service;

namespace api.Features.Auth
{
	[Produces("application/json")]
	[Route("[controller]")]
	public class AuthController : Controller
	{
		private readonly IAuthService authService;

		public AuthController(IAuthService authService) => this.authService = authService;

		/// <summary>
		/// Authorizes user
		/// </summary>
		/// <param name="model">User credentials</param>
		/// <response code="200">User authorized. Returns access token</response>
		/// <response code="400">If model is null</response>
		/// <response code="404">If credentials are wrong, or user is not registred yet</response>
		[HttpPost("login")]
		public ActionResult Post([FromBody]AuthModel model)
		{
			var result = authService.Login(model);

			return StatusCode(result.StatusCode, result.Message);
		}

		/// <summary>
		/// Creates a new user
		/// </summary>
		/// <remarks>
		/// Note that ID is a autogenerated GUID, so you should not provide it in request
		/// </remarks>
		/// <param name="model">User information</param>
		/// <response code="201">User created. Returns access token</response>
		/// <response code="400">If model is null</response>
		/// <response code="409">If Email is not available</response>
		[HttpPost("register")]
		public ActionResult Post([FromBody]AccountModel model)
		{
			var result = authService.Register(model);

			return StatusCode(result.StatusCode, result.Message);
		}
	}
}
